[project]
authors = ["Antonio Camargo <antoniop.camargo@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Create a MMseqs2 virus protein database with ICTV taxonomy"
name = "ictv-mmseqs2-protein-database"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
taxopy = ">=0.13.0,<0.14"
taxonkit = ">=0.18.0,<0.19"
mmseqs2 = ">=17.b804f,<18"
csvtk = ">=0.32.0,<0.33"
unidecode = ">=1.3.8,<2"
